add tcllib build

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -2,12 +2,22 @@ name: Windows
 on:
   workflow_dispatch:
     inputs:
-      tcl-labels:
+      tcl-tags:
         required: true
         type: choice
         options:
+          - '["core-9-0-3"]'
           - '["core-9-1-a1-rc"]'
-        default: '["core-9-1-a1-rc"]'
+        default: '["core-9-0-3"]'
+      tcllib-tags:
+        options:
+          - '["tcllib-2-0"]'
+        default: '["tcllib-2-0"]'
+      tklib-tags:
+        options:
+          - '["tklib-0.9"]'
+        default: '["tklib-0.9"]'
+    
 permissions:
   contents: read
 env:
@@ -27,30 +37,58 @@ jobs:
           - ""
           # - "OPTS=symbols"
           # - "OPTS=static"
+        tcl-tag: ${{ fromJSON(github.event.inputs.tcl-tags) }}
+        tcllib-tag: ${{ fromJSON(github.event.inputs.tcllib-tags) }}
+        tklib-tag: ${{ fromJSON(github.event.inputs.tklib-tags) }}
     steps:
+      - name: Prepare
+        run: |
+          mkdir "C:\Tcl"
+          echo "INSTALL_DIR=C:\Tcl" >> $GITHUB_ENV
+          if ( ${{ $matrix.tcl-tag }} -match "core-9-0.*" ) {
+            echo "TCLSH=$INSTALL_DIR/bin/tclsh90.exe" >> $GITHUB_ENV
+          } else if ( ${{ $matrix.tcl-tag }} -match "core-9-1.*" ) {
+            echo "TCLSH=$INSTALL_DIR/bin/tclsh91.exe" >> $GITHUB_ENV
+          } else {
+            echo "Unable to set TCLSH."
+            exit 1
+          }
+        working-directory: tk/generic
       - name: Checkout Tk
         uses: actions/checkout@v6
         with:
           repository: tcltk/tk
-          ref: ${{ matrix.tcl-label }}
+          ref: ${{ matrix.tcl-tag }}
           path: tk
       - name: Checkout Tcl
         uses: actions/checkout@v6
         with:
           repository: tcltk/tcl
-          ref: ${{ matrix.tcl-label }}
+          ref: ${{ matrix.tcl-tag }}
           path: tcl
+      - name: Checkout Tcllib
+        uses: actions/checkout@v6
+        with:
+          repository: tcltk/tcllib
+          ref: ${{ matrix.tcllib-tag }}
+          path: tcllib
+      - name: Checkout Tklib
+        uses: actions/checkout@v6
+        with:
+          repository: tcltk/tklib
+          ref: ${{ matrix.tklib-tag }}
+          path: tklib
       - name: Init MSVC
         uses: ilammy/msvc-dev-cmd@v1
         with:
           arch: x64
       - name: Build Tcl (${{ matrix.config }})
         run: |
-          &nmake -f makefile.vc release ${{ matrix.config }}
+          &nmake -f makefile.vc release ${{ matrix.config }} INSTALL_DIR=${{ env.install_dir }}
         working-directory: tcl/win
       - name: Install Tcl  (${{ matrix.config }})
         run: |
-          &nmake -f makefile.vc install ${{ matrix.config }}
+          &nmake -f makefile.vc install ${{ matrix.config }} INSTALL_DIR=${{ env.install_dir }}
           if ($lastexitcode -ne 0) {
              throw "nmake exit code: $lastexitcode"
           }
@@ -59,14 +97,14 @@ jobs:
         working-directory: tcl/win
       - name: Build Tk (${{ matrix.config }})
         run: |
-          &nmake -f makefile.vc all ${{ matrix.config }}
+          &nmake -f makefile.vc all ${{ matrix.config }} INSTALL_DIR=${{ env.install_dir }}
           if ($lastexitcode -ne 0) {
              throw "nmake exit code: $lastexitcode"
           }
       - name: Build Test Harness (${{ matrix.config }})
         if: 0 == 1
         run: |
-          &nmake -f makefile.vc tktest ${{ matrix.config }}
+          &nmake -f makefile.vc tktest ${{ matrix.config }} INSTALL_DIR=${{ env.install_dir }}
           if ($lastexitcode -ne 0) {
              throw "nmake exit code: $lastexitcode"
           }
@@ -95,13 +133,13 @@ jobs:
         timeout-minutes: 10
       - name: Build Help (${{ matrix.config }})
         run: |
-          &nmake -f makefile.vc htmlhelp ${{ matrix.config }}
+          &nmake -f makefile.vc htmlhelp ${{ matrix.config }} INSTALL_DIR=${{ env.install_dir }}
           if ($lastexitcode -ne 0) {
              throw "nmake exit code: $lastexitcode"
           }
       - name: Install Tk (${{ matrix.config }})
         run: |
-          &nmake -f makefile.vc install ${{ matrix.config }}
+          &nmake -f makefile.vc install ${{ matrix.config }} INSTALL_DIR=${{ env.install_dir }}
           if ($lastexitcode -ne 0) {
              throw "nmake exit code: $lastexitcode"
           }
@@ -109,7 +147,10 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: "Tcl-Tk Release Distribution (Win64)"
-          path: "C:/Tcl"
+          path: ${{ env.install_dir }}
+      - name: Install TclLib
+        run: |
+          &${{ env.install_dir }}\bin\tclsh
   gcc:
     if: 1 == 0
     runs-on: windows-2025
@@ -124,7 +165,7 @@ jobs:
           #- "--enable-symbols=mem"
           #- "--enable-symbols=all"
           #- "--disable-shared"
-        tcl-label: ${{ fromJSON(github.event.inputs.tcl-labels) }}
+        tcl-tag: ${{ fromJSON(github.event.inputs.tcl-tags) }}
     steps:
       - name: Install MSYS2
         uses: msys2/setup-msys2@v2
@@ -135,13 +176,13 @@ jobs:
         uses: actions/checkout@v6
         with:
           repository: tcltk/tk
-          ref: ${{ matrix.tcl-label }}
+          ref: ${{ matrix.tcl-tag }}
           path: tk
       - name: Checkout Tcl
         uses: actions/checkout@v6
         with:
           repository: tcltk/tcl
-          ref: ${{ matrix.tcl-label }}
+          ref: ${{ matrix.tcl-tag }}
           path: tcl
       - name: Prepare
         run: |
